/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author dcris
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        // Centraliza a janela
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        itemProdutos = new javax.swing.JMenuItem();
        itemCategorias = new javax.swing.JMenuItem();
        menuGerenciamentos = new javax.swing.JMenu();
        itemGerenciarProdutos = new javax.swing.JMenuItem();
        itemGerenciarCategorias = new javax.swing.JMenuItem();
        menuMovimentacoes = new javax.swing.JMenu();
        itemRegistrarMovimentacao = new javax.swing.JMenuItem();
        itemGerenciarMovimentacao = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemRelatorio = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Bem-vindo ao Sistema de Controle de Estoque");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtitulo.setText("Use o menu acima para navegar entre as funcionalidades");

        menuCadastros.setText("Cadastros");

        itemProdutos.setText("Produtos");
        itemProdutos.addActionListener(this::itemProdutosActionPerformed);
        menuCadastros.add(itemProdutos);

        itemCategorias.setText("Categorias");
        itemCategorias.addActionListener(this::itemCategoriasActionPerformed);
        menuCadastros.add(itemCategorias);

        jMenuBar1.add(menuCadastros);

        menuGerenciamentos.setText("Gerenciamentos");

        itemGerenciarProdutos.setText("Gerenciar Produtos");
        itemGerenciarProdutos.addActionListener(this::itemGerenciarProdutosActionPerformed);
        menuGerenciamentos.add(itemGerenciarProdutos);

        itemGerenciarCategorias.setText("Gerenciar Categorias");
        itemGerenciarCategorias.addActionListener(this::itemGerenciarCategoriasActionPerformed);
        menuGerenciamentos.add(itemGerenciarCategorias);

        jMenuBar1.add(menuGerenciamentos);

        menuMovimentacoes.setText("Movimentações");

        itemRegistrarMovimentacao.setText("Registrar Movimentação");
        itemRegistrarMovimentacao.addActionListener(this::itemRegistrarMovimentacaoActionPerformed);
        menuMovimentacoes.add(itemRegistrarMovimentacao);

        itemGerenciarMovimentacao.setText("Gerenciar Movimentação");
        itemGerenciarMovimentacao.addActionListener(this::itemGerenciarMovimentacaoActionPerformed);
        menuMovimentacoes.add(itemGerenciarMovimentacao);

        jMenuBar1.add(menuMovimentacoes);

        menuRelatorios.setText("Relatórios");

        itemRelatorio.setText("Gerar Relatório");
        itemRelatorio.addActionListener(this::itemRelatorioActionPerformed);
        menuRelatorios.add(itemRelatorio);

        jMenuBar1.add(menuRelatorios);

        menuSistema.setText("Sistema");

        itemSair.setText("Sair");
        itemSair.addActionListener(this::itemSairActionPerformed);
        menuSistema.add(itemSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegistrarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarMovimentacaoActionPerformed
        abrirTelaMovimentacao();
    }//GEN-LAST:event_itemRegistrarMovimentacaoActionPerformed

    private void itemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutosActionPerformed
        abrirTelaProduto();
    }//GEN-LAST:event_itemProdutosActionPerformed

    private void itemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriasActionPerformed
        abrirTelaCategoria();
    }//GEN-LAST:event_itemCategoriasActionPerformed

    private void itemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioActionPerformed
        abrirTelaRelatorio();
    }//GEN-LAST:event_itemRelatorioActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        sairSistema();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemGerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarProdutosActionPerformed
        abrirTelaGerenciarProduto();
    }//GEN-LAST:event_itemGerenciarProdutosActionPerformed

    private void itemGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarCategoriasActionPerformed
        abrirTelaGerenciarCategoria();
    }//GEN-LAST:event_itemGerenciarCategoriasActionPerformed

    private void itemGerenciarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarMovimentacaoActionPerformed
        abrirTelaGerenciarMovimentacao();
    }//GEN-LAST:event_itemGerenciarMovimentacaoActionPerformed
    private void abrirTelaCategoria() {

        try {
            FrmCadastroCategoria telaCategoria = new FrmCadastroCategoria();
            telaCategoria.setLocationRelativeTo(null);
            telaCategoria.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de categorias: " + erro.getMessage()
            );
        }
    }

    private void abrirTelaProduto() {

        try {
            FrmCadastroProduto telaProduto = new FrmCadastroProduto();
            telaProduto.setLocationRelativeTo(null);
            telaProduto.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de produtos: " + erro.getMessage()
            );
        }
    }

    private void abrirTelaMovimentacao() {

        try {
            FrmCadastroMovimentacao telaMovimentacao = new FrmCadastroMovimentacao();
            telaMovimentacao.setLocationRelativeTo(null);
            telaMovimentacao.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de movimentações: " + erro.getMessage()
            );
        }
    }

    private void abrirTelaRelatorio() {

        try {
            FrmRelatorios telaRelatorio = new FrmRelatorios();
            telaRelatorio.setLocationRelativeTo(null);
            telaRelatorio.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de relatórios: " + erro.getMessage()
            );
        }
    }

    private void sairSistema() {

        Object[] opcoes = {"Sim", "Não"};

        int resposta = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Deseja sair do sistema?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]
        );

        if (resposta == 0) {
            System.exit(0);
        }
    }

    private void abrirTelaGerenciarProduto() {

        try {
            FrmGerenciaProduto telaGerenciarProduto = new FrmGerenciaProduto();
            telaGerenciarProduto.setLocationRelativeTo(null);
            telaGerenciarProduto.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de gerenciamento de produtos: " + erro.getMessage()
            );
        }
    }

    private void abrirTelaGerenciarCategoria() {

        try {
            FrmGerenciaCategoria telaGerenciarCategoria = new FrmGerenciaCategoria();
            telaGerenciarCategoria.setLocationRelativeTo(null);
            telaGerenciarCategoria.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de gerenciamento de categorias: " + erro.getMessage()
            );
        }
    }

    private void abrirTelaGerenciarMovimentacao() {

        try {
            FrmGerenciaMovimentacao telaGerenciarMovimentacao = new FrmGerenciaMovimentacao();
            telaGerenciarMovimentacao.setLocationRelativeTo(null);
            telaGerenciarMovimentacao.setVisible(true);
        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao abrir a tela de gerenciamento de movimentação: " + erro.getMessage()
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCategorias;
    private javax.swing.JMenuItem itemGerenciarCategorias;
    private javax.swing.JMenuItem itemGerenciarMovimentacao;
    private javax.swing.JMenuItem itemGerenciarProdutos;
    private javax.swing.JMenuItem itemProdutos;
    private javax.swing.JMenuItem itemRegistrarMovimentacao;
    private javax.swing.JMenuItem itemRelatorio;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuGerenciamentos;
    private javax.swing.JMenu menuMovimentacoes;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
